### ISSUE TITLE
Not streaming output anymore

### ISSUE THREAD

**Issue by jayd3e** [flynn-archive/slugbuilder#24] opened 2014-06-12 13:49 UTC
On the client side, when I call `git push flynn master`, I only receive a small amount of output:

```
Total 0 (delta 0), reused 0 (delta 0)
-----> Building clusterflunk...
-----> Creating release...
=====> Application deployed
To ssh://git@clusterflunkapps.com:55006/clusterflunk.git
 + 93f708c...9e129bd master -> master (forced update)
```

Whereas on the server-side, doing a quick `docker logs -f <id>`, gives a lot more output:

![output](http://cl.ly/image/390M2v3Q1o2H/Screen%20Shot%202014-06-12%20at%208.45.50%20AM.png)

It appears that all of the output in `flynn-receive` is getting streamed properly, but not the output from the buildpack itself.  I should note that the push completes fine.

**Comment by titanous** [comment] 2014-06-12 15:50
What version of Docker are you using?

**Comment by jayd3e** [comment] 2014-06-12 16:22
The 1.0.0 release.

**Comment by titanous** [comment] 2014-06-12 16:49
This is a duplicate of flynn/flynn#18.

**Closed as completed by titanous** 2014-06-12 16:49 UTC
